# Generated by Django 2.2.1 on 2019-05-07 02:36

from django.db import migrations, models
import django.db.models.deletion
import test_smart_soft_deletion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_smart_soft_deletion.Country', verbose_name='Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('category', models.ForeignKey(null=True, on_delete=models.SET(test_smart_soft_deletion.models.create_category_default), to='test_smart_soft_deletion.Category', verbose_name='Category')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_smart_soft_deletion.Industry', verbose_name='Industry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
