# Generated by Django 2.2.1 on 2019-05-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_smart_soft_deletion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_deleted',
            new_name='_is_deleted',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='is_deleted',
            new_name='_is_deleted',
        ),
        migrations.RenameField(
            model_name='industry',
            old_name='is_deleted',
            new_name='_is_deleted',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_deleted',
            new_name='_is_deleted',
        ),
    ]
