# Generated by Django 2.2.1 on 2019-05-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_smart_soft_deletion', '0002_auto_20190507_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='industry',
            name='founders',
            field=models.ManyToManyField(to='test_smart_soft_deletion.Founder', verbose_name='Founders'),
        ),
    ]
